[package]
name = "lab4"
version = "0.1.0"
authors = ["btg99 <btg99email@gmail.com>"]
edition = "2018"

[dependencies]
socket2 = "0.3.19"
rand = "0.8"
streaming-stats = "0.2.3"
structopt = { version = "0.3", default-features = false }