[package]
name = "lab4"
version = "0.1.0"
authors = ["btg99 <btg99email@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawsock = "0.3"
time = "0.1.42"